import {useEffect,useLayoutEffect,useRef,useState,useMemo} from 'react';
import {api} from '../lib/api';
import type {ComicBook} from '../types/comic';
import type {CollectionSort,LibraryRoot,MediaNode,ViewMode} from '../types/media';
import type {LogicalGroup,BookCatalogue,BookCorrection} from '../types/catalogue';
import {useI18n} from '../lib/i18n';
import {nodeDisplayTitle,errorMessage,naturalCompare} from '../lib/format';
import {PosterGrid} from './PosterGrid';
import {MediaCard} from './MediaCard';
import {BookPosterCard} from './BookPosterCard';
import {ContextMenu,type NodeAction} from './ContextMenu';
import {ComicDetailPage,LogicalBookDetail} from '../pages/ComicDetailPage';
import {Icon} from './Icon';
import {Select} from './Select';
import {EmptyState} from './EmptyState';
import {LoadingState} from './LoadingState';
import {isolateModalSiblings} from '../lib/modalA11y';
import {bookCollectionEntries} from '../lib/bookCollection';

type Destination={category:string;group:string|null};
export type SmartPresentation={title:string;path:string;count:number;totalCount:number;detail:boolean;nodes:MediaNode[];visibleNodes:MediaNode[];back:()=>void;home:()=>void};
const destinations=new Map<number,Destination>();
function historyDestination(root:number):Destination|undefined {const value=window.history.state?.smartMixed;return value?.root===root&&typeof value.destination?.category==='string'&&(value.destination.group===null||typeof value.destination.group==='string')?value.destination:undefined;}
type Props={root:LibraryRoot;sort:CollectionSort;filter:string;tagFilterId:number|null;viewMode:ViewMode;coverRevision:number;onRead:(book:ComicBook)=>void;onPresentation:(value:SmartPresentation)=>void;onOpenNode:(node:MediaNode)=>void;onNodeAction?:(action:NodeAction,node:MediaNode)=>void;onBangumi:(node:MediaNode)=>void;onRetryCover:(node:MediaNode,failed?:boolean)=>void;editMode:boolean;selectedNodeIds:ReadonlySet<number>;onSelect:(node:MediaNode)=>void;fallback:React.ReactNode};

/** Data projection only: the existing Browse toolbar, PosterGrid, MediaCard and book detail render it. */
export function SmartMixedBrowser({root,sort,filter,tagFilterId,viewMode,coverRevision,onRead,onPresentation,onOpenNode,onNodeAction,onBangumi,onRetryCover,editMode,selectedNodeIds,onSelect,fallback}:Props) {
 const {language,t}=useI18n();const [catalogue,setCatalogue]=useState<BookCatalogue|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const [destination,setDestination]=useState(()=>historyDestination(root.id)??destinations.get(root.id)??{category:'',group:null});
 const [menu,setMenu]=useState<{x:number;y:number;path:string;node?:MediaNode|null;book?:ComicBook}|null>(null);
 const [correction,setCorrection]=useState('');const [action,setAction]=useState<BookCorrection>('CATEGORY');const [target,setTarget]=useState('');
 const generation=useRef(0),pendingScroll=useRef<number|null>(null),dialog=useRef<HTMLDivElement>(null);
 const load=async()=>{const request=++generation.current;try{const next=await api.getBookCatalogue(root.id);if(request===generation.current){setCatalogue(next);setError('');}}catch(e){if(request===generation.current)setError(errorMessage(e));}};
 useEffect(()=>{setDestination(historyDestination(root.id)??destinations.get(root.id)??{category:'',group:null});setCatalogue(null);void load();return()=>{generation.current++;};},[root.id,coverRevision]);
 const navigate=(next:Destination,record=true)=>{const state=window.history.state;destinations.set(root.id,next);pendingScroll.current=0;
  if(state?.m2ShelfNavigation){const previous=state.smartMixed?.root===root.id?state.smartMixed:{root:root.id,destination,depth:0};if(record)window.history.replaceState({...state,smartMixed:{...previous,scrollTop:document.querySelector('.content-scroll')?.scrollTop??0}},'');window.history[record?'pushState':'replaceState']({...state,smartMixed:{root:root.id,destination:next,depth:record?(previous.depth??0)+1:0,scrollTop:0}},'');}setDestination(next);};
 const localBack=()=>{if(window.history.state?.smartMixed?.root===root.id&&window.history.state.smartMixed.depth>0)window.history.back();else navigate({category:destination.group?destination.category:destination.category.split('/').slice(0,-1).join('/'),group:null},false);};
 useEffect(()=>{const back=(event:Event)=>{if(!destination.category&&!destination.group)return;event.preventDefault();localBack();};const pop=()=>{const next=historyDestination(root.id);if(next){pendingScroll.current=window.history.state.smartMixed.scrollTop??0;destinations.set(root.id,next);setDestination(next);}};window.addEventListener('m2shelf-logical-back',back);window.addEventListener('popstate',pop);return()=>{window.removeEventListener('m2shelf-logical-back',back);window.removeEventListener('popstate',pop);};},[destination,root.id]);
 useLayoutEffect(()=>{if(!catalogue||pendingScroll.current===null)return;const scroll=document.querySelector('.content-scroll');if(scroll)scroll.scrollTop=pendingScroll.current;pendingScroll.current=null;},[destination,catalogue]);
 useEffect(()=>{if(!menu)return;const close=()=>setMenu(null);const key=(e:KeyboardEvent)=>{if(e.key==='Escape')close();};window.addEventListener('pointerdown',close);window.addEventListener('keydown',key);return()=>{window.removeEventListener('pointerdown',close);window.removeEventListener('keydown',key);};},[menu]);
 useEffect(()=>{if(!correction)return;const release=isolateModalSiblings(dialog.current);const focus=document.activeElement as HTMLElement|null;dialog.current?.querySelector<HTMLElement>('button')?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!busy){e.preventDefault();e.stopImmediatePropagation();setCorrection('');}if(e.key==='Tab'){const list=Array.from(dialog.current?.querySelectorAll<HTMLElement>('button:not(:disabled),[role=combobox]:not(:disabled)')??[]);const current=list.indexOf(document.activeElement as HTMLElement);if(list.length){e.preventDefault();list[(current+(e.shiftKey?-1:1)+list.length)%list.length].focus();}}};window.addEventListener('keydown',key,true);return()=>{window.removeEventListener('keydown',key,true);release();focus?.focus();};},[correction,busy]);
 const group=catalogue?.groups.find(g=>g.id===destination.group);
 function relative(book:ComicBook){const base=root.path.replaceAll('\\','/').replace(/\/$/,'')+'/';const path=book.sourcePath?.replaceAll('\\','/');return path?.toLowerCase().startsWith(base.toLowerCase())?path.slice(base.length):book.displayName;}
 const title=(g:LogicalGroup)=>g.coverNode?nodeDisplayTitle(g.coverNode,language):g.title;
 const match=(name:string,node?:MediaNode|null)=>name.toLocaleLowerCase().includes(filter.trim().toLocaleLowerCase())&&(tagFilterId===null||!!node?.userTags.some(tag=>tag.id===tagFilterId));
 const candidates=useMemo(()=>catalogue?bookCollectionEntries(root,catalogue,destination.category).map(entry=>({...entry,name:entry.node?nodeDisplayTitle(entry.node,language):entry.name})):[],[catalogue,root,destination.category,language]);
 const entries=candidates.filter(e=>match(e.name,e.node));
 entries.sort((a,b)=>{let value=naturalCompare(a.name,b.name);if(!sort.startsWith('title-')){const stamp=(e:typeof a)=>e.group?Math.max(...e.group.books.map(book=>sort.startsWith('added-')?book.id:Date.parse(sort.startsWith('watched-')?book.progress?.lastReadAt??'':book.modifiedAt)||0)):Date.parse(e.node?.updatedAt??'')||0;value=stamp(a)-stamp(b);}return sort.endsWith('-desc')?-value:value;});
 const nodeKey=candidates.filter(e=>e.node).map(e=>e.node!.id).join(',');
 useLayoutEffect(()=>onPresentation({title:group?title(group):destination.category.split('/').pop()||root.displayName,path:destination.category?root.path+'/'+destination.category:root.path,count:group?.books.length??entries.length,totalCount:candidates.length,detail:!!group,nodes:candidates.flatMap(e=>e.node?[e.node]:[]),visibleNodes:entries.flatMap(e=>e.node?[e.node]:[]),back:localBack,home:()=>navigate({category:'',group:null})}),[destination,catalogue,entries.length,nodeKey,entries.map(e=>e.node?.id??e.group?.id).join(','),language,root.displayName]);
 const openCorrection=(path:string,value:BookCorrection)=>{setMenu(null);setAction(value);setTarget('');setCorrection(path);};
 const correct=async()=>{if(!catalogue)return;setBusy(true);try{await api.correctBookOrganization(root.id,correction,action,action==='ASSIGN'?target:null,catalogue.revision);setCorrection('');window.dispatchEvent(new Event('m2shelf-metadata-changed'));await load();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}};
 const menuAt=(event:React.MouseEvent,path:string,node?:MediaNode|null,book?:ComicBook)=>{event.preventDefault();setMenu({x:Math.min(event.clientX,window.innerWidth-245),y:Math.min(event.clientY,window.innerHeight-350),path,node,book});};
 const correctionItems=menu&&<>{(['CATEGORY','SERIES','ASSIGN','INDEPENDENT','AUTOMATIC'] as const).map(value=><button key={value} type="button" disabled={(value==='CATEGORY'||value==='SERIES')&&!catalogue?.directories.some(d=>d.path===menu.path)} onClick={()=>openCorrection(menu.path,value)}><Icon name="edit"/>{t(value==='CATEGORY'?'smart.category':value==='SERIES'?'smart.series':value==='ASSIGN'?'smart.assign':value==='INDEPENDENT'?'smart.independent':'smart.automatic')}</button>)}<span className="menu-divider"/></>;
 const open=(entry:typeof entries[number])=>{if(!entry.group)navigate({category:entry.path,group:null});else if(entry.group.kind==='WORK'&&entry.group.books.length===1)onRead(entry.group.books[0]);else navigate({...destination,group:entry.group.id});};
 const node=group?.coverNode;
 return <div className="smart-catalogue">
  {error&&<div className="inline-error" role="alert">{error}<button type="button" onClick={()=>void load()}>{t('common.retry')}</button></div>}
  {!catalogue&&!error?<LoadingState/>:!catalogue?fallback:group?node?<ComicDetailPage detail={{node,binding:node.binding??null,children:[],mediaFiles:[],resourceFiles:[],breadcrumbs:[{id:node.id,displayName:nodeDisplayTitle(node,language)}],comicBooks:group.books}} loading={false} rootLabel={root.displayName} onRoot={()=>navigate({category:'',group:null})} onBreadcrumb={()=>localBack()} onBack={localBack} onReadComic={onRead} onBookMenu={(event,book)=>menuAt(event,relative(book),null,book)} coverRevision={coverRevision} onBangumi={()=>onBangumi(node)} onBangumiNode={onBangumi} onRetryCover={failed=>onRetryCover(node,failed)} onRetryCoverNode={onRetryCover} onClearBangumi={()=>onNodeAction?.('clear-bangumi',node)} onOpenBangumi={()=>void api.openBangumiSubject(node.id)} onReveal={()=>onNodeAction?.('explorer',node)} onMenu={event=>menuAt(event,group.relativePath,node)} onOpenChild={onOpenNode} onOpenResource={()=>undefined} onRevealResource={()=>undefined} onPlay={()=>undefined} onRevealMedia={()=>undefined}/>:<LogicalBookDetail group={group} root={root} revision={coverRevision} onBack={localBack} onRoot={()=>navigate({category:'',group:null})} onRead={onRead} onBookMenu={(event,book)=>menuAt(event,relative(book),null,book)} onMenu={event=>menuAt(event,group.relativePath,null,group.books[0])}/>:entries.length===0?<EmptyState compact icon={filter.trim()||tagFilterId!==null?'search':'folder'} title={t(filter.trim()||tagFilterId!==null?'browse.noMatch':'browse.empty')} description={t(filter.trim()||tagFilterId!==null?'browse.noMatchDescription':'browse.emptyFolderDescription')}/>:<PosterGrid nodes={[]} viewMode={viewMode} onOpen={onOpenNode} onMenu={()=>undefined} onBangumi={onBangumi} onRetryCover={onRetryCover} coverRevision={coverRevision}>
   {entries.map(entry=>entry.node?<MediaCard key={entry.group?.id??entry.path} node={entry.node} viewMode={viewMode} onOpen={()=>open(entry)} onMenu={event=>menuAt(event,entry.path,entry.node,entry.group?.books[0])} onBangumi={onBangumi} onRetryCover={onRetryCover} coverRevision={coverRevision} editMode={editMode} selected={selectedNodeIds.has(entry.node.id)} onSelect={onSelect}/>:entry.group?<BookPosterCard key={entry.group.id} book={entry.group.books[0]} title={entry.name} count={entry.group.books.length} series={entry.group.kind==='SERIES'} root={root} viewMode={viewMode} revision={coverRevision} onOpen={()=>open(entry)} onMenu={event=>menuAt(event,entry.path,null,entry.group?.books[0])} editMode={editMode}/>:null)}
  </PosterGrid>}
  {menu?.node?<ContextMenu node={menu.node} x={menu.x} y={menu.y} onClose={()=>setMenu(null)} onAction={(value,current)=>onNodeAction?.(value,current)} organizationActions={<>{correctionItems}<button type="button" onClick={()=>{onOpenNode(menu.node!);setMenu(null);}}><Icon name="folder"/>{t('smart.physical')}</button></>}/>:menu&&<div className="context-menu" role="menu" tabIndex={-1} style={{left:Math.max(8,menu.x),top:Math.max(8,menu.y)}} onPointerDown={event=>event.stopPropagation()}><p>{menu.book?.displayName??menu.path}</p>{correctionItems}{menu.book&&<button type="button" onClick={()=>{void api.revealComicBook(menu.book!.id).catch(e=>setError(errorMessage(e)));setMenu(null);}}><Icon name="external"/>{t('files.reveal')}</button>}</div>}
  {correction&&<div ref={dialog} className="modal-backdrop" data-unsaved-edit="true" onMouseDown={event=>{if(event.target===event.currentTarget&&!busy)setCorrection('');}}><section className="smart-organization-dialog" role="dialog" aria-modal="true" aria-label={t('smart.correct')}><h2>{t('smart.correct')}</h2><p>{correction}</p><Select aria-label={t('smart.correct')} value={action} disabled={busy} onChange={event=>setAction(event.target.value as BookCorrection)}>{(['CATEGORY','SERIES','ASSIGN','INDEPENDENT','AUTOMATIC'] as const).map(value=><option key={value} value={value} disabled={(value==='CATEGORY'||value==='SERIES')&&!catalogue?.directories.some(d=>d.path===correction)}>{t(value==='CATEGORY'?'smart.category':value==='SERIES'?'smart.series':value==='ASSIGN'?'smart.assign':value==='INDEPENDENT'?'smart.independent':'smart.automatic')}</option>)}</Select>{action==='ASSIGN'&&<Select aria-label={t('smart.series')} value={target} onChange={event=>setTarget(event.target.value)}><option value="">—</option>{catalogue?.groups.filter(g=>g.kind==='SERIES'&&g.relativePath!==correction).map(g=><option key={g.id} value={g.relativePath}>{g.title}</option>)}</Select>}<div className="dialog-actions"><button className="button secondary" type="button" disabled={busy} onClick={()=>setCorrection('')}>{t('common.cancel')}</button><button className="button primary" type="button" disabled={busy||action==='ASSIGN'&&!target} onClick={()=>void correct()}>{t('common.save')}</button></div></section></div>}
 </div>;
}
